version: '2'

services:
  db:
      image: postgres
      environment:
        - POSTGRES_DB=hw4db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=passw0rd
      expose:
        - "5432"
      volumes:
        - data-volume:/var/lib/postgresql/data
  stock:
      build: ./src
      user: root
      command: "/hw4/runserver.sh"
      ports:
        - "12345:12345"
      depends_on: 
        - db
volumes:
   data-volume: 

